### PR TITLE
changing center to centroid

### PR DESCRIPTION
**Pull request by danielmwatkins**
Addresses an issue where there is a mismatch between the names of columns in flow generator vs the site locations csv file.

### CODE REVIEW

**Comment by danielmwatkins** [comment]
Note, I also added a couple of newlines so that you don't have to scroll to the right to read the docstring.

**Comment by danielmwatkins** [comment]
OK, this doesn't actually fix the issue. Trying something else.

**Comment by danielmwatkins** [comment]
Rather than changing all the center_lat/center_lon to centroids, I just changed the j2 file to say center_lat and center_lon. It seems like this fixed the issue on my end.

**Review by tdivoll — APPROVED** [review]
I agree, it is simpler to just make that one change.

**Pull request merged**
