### PR TITLE
62 deprecate getiftversion in favor of iftversion

### PR DESCRIPTION
**Pull request by cpaniaguam**
#62

### CODE REVIEW

**Comment by cpaniaguam** [comment]
After merging https://github.com/WilhelmusLab/IceFloeTracker.jl/pull/332 CI should pass.

**Review by tdivoll — APPROVED** [review]
All good, everything passes! And codecov is better now too.

**Review by tdivoll — COMMENTED** [review]
Maybe add in the docstrings on L70. ```* `iftversion`: The current version of IceFloeTracker is loaded into the function automatically` ```?

**Comment by cpaniaguam** [comment]
> Maybe add in the docstrings on L70. `` * `iftversion`: The current version of IceFloeTracker is loaded into the function automatically` ``?

In what file?

**Comment by cpaniaguam** [comment]
> I can update the docstring in `h5,jl` on PR #45 !

Thanks! I'll merge this PR then.

**Pull request merged**
