### PR TITLE
change v to z in line 113

### PR DESCRIPTION
**Pull request by danielmwatkins**
Weird error on my computer goes away if we change `! -v` to `-z`

### CODE REVIEW

**Comment by tdivoll** [comment]
@broarr I did a little digging and it seems like `! -v ${var+x}` will check if the variable is unset, whereas `-z ${var+x}` will check if there is a value stored in the variable. The -z approach seems to work on @danielmwatkins machine and it still works  the same as it did for me with ! -v.

**Comment by cpaniaguam** [comment]
Interesting situation. But.. what's triggering this bug?

**Comment by tdivoll** [comment]
@cpaniaguam It is still a bit of a mystery...we checked that @danielmwatkins machine was returning `Darwin` for the OS and that there was no env var for `CYLC_VERSION`. My only last thought is that the `-v` option was added to bash version 4.2, but that was released in 2011, so it must be available on just about all computers.

**Review by tdivoll — APPROVED** [review]
I tested this locally on my macos s well as on Oscar (linux), and the script runs fine on both with the `-z` option.

**Comment by tdivoll** [comment]
@danielmwatkins Would you like to hit the Merge button? We typically let the creator of the PR do the honors after approval!

**Comment by cpaniaguam** [comment]
Merging.

**Comment by danielmwatkins** [comment]
I didn’t see this until now - next time I’d love to hit merge!-DanielOn Nov 28, 2023, at 11:46, Timothy Divoll ***@***.***> wrote:﻿
@danielmwatkins Would you like to hit the Merge button? We typically let the creator of the PR do the honors after approval!

**Pull request merged**
